export const LOGIN_GOOGLE = 'app/LOGIN_GOOGLE';
export const LOGOUT_GOOGLE = 'app/LOGOUT_GOOGLE';
export const LOGIN_GOOGLE_SUCCESS = 'app/LOGIN_GOOGLE_SUCESS';
export const LOGOUT_GOOGLE_SUCCESS = 'app/LOGOUT_GOOGLE_SUCCESS';
export const LOGIN_GOOGLE_ERROR = 'app/LOGIN_GOOGLE_ERROR';
